"""Embed the built-in level files (levels/*.json) into the game.

Writes src/levels_gen.rs with one include_str! per file. Run after adding, renaming or
removing a level file (editing an existing file only needs a rebuild).

    python scripts/import_levels.py
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
LEVELS = ROOT / "levels"
OUT = ROOT / "src" / "levels_gen.rs"


def main() -> int:
    files = sorted(LEVELS.glob("*.json")) if LEVELS.is_dir() else []
    bad = 0
    lines = [
        "// Generated by scripts/import_levels.py - do not edit.",
        "/// (file name, JSON text) for every built-in level.",
        "pub const LEVELS: &[(&str, &str)] = &[",
    ]
    for f in files:
        try:
            json.loads(f.read_text(encoding="utf-8"))
        except (ValueError, UnicodeDecodeError) as e:
            print(f"skipping {f.name}: not valid JSON ({e})")
            bad += 1
            continue
        lines.append(f'    ("{f.name}", include_str!("../levels/{f.name}")),')
    lines.append("];")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(files) - bad} level(s)")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
