"""Import generated art into the game.

Reads the art contract in D:\\projects\\ElementalLegends-art\\sheets\\ (manifest.json for
sprite sheets, terrain\\terrain.json for tilesets), converts every PNG into a raw
pixel blob in assets/art/, and writes src/art_gen.rs, which embeds the blobs with
include_bytes! so the game (desktop and handheld) is still a single executable.

Blob format: u32 width, u32 height (little endian), then width*height u32 pixels
as 0xAARRGGBB (0 = transparent).

Usage (from the repo root, Windows or WSL):  python scripts/import_art.py [art_dir]
Sprites missing from the manifest simply keep their code-drawn fallback.
"""
import json
import struct
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
ART = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(r"D:\projects\ElementalLegends-art")
if not ART.exists():
    ART = Path("/mnt/d/projects/ElementalLegends-art")
SHEETS = ART / "sheets"
OUT = ROOT / "assets" / "art"
GEN = ROOT / "src" / "art_gen.rs"


def blob(src: Path, dest: Path):
    im = Image.open(src).convert("RGBA")
    data = bytearray(struct.pack("<II", im.width, im.height))
    raw = im.tobytes()
    for i in range(0, len(raw), 4):
        r, g, b, a = raw[i], raw[i + 1], raw[i + 2], raw[i + 3]
        data += struct.pack("<I", 0 if a < 128 else (0xFF000000 | (r << 16) | (g << 8) | b))
    dest.write_bytes(data)
    return im.width, im.height


def rust_str(s: str) -> str:
    return json.dumps(s)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for old in OUT.glob("*.bin"):
        old.unlink()
    sprites, terrain = [], []

    manifest = SHEETS / "manifest.json"
    if manifest.exists():
        m = json.loads(manifest.read_text())
        for name, sp in sorted(m.get("sprites", {}).items()):
            src = SHEETS / sp["file"]
            if not src.exists():
                print("missing", src)
                continue
            w, h = blob(src, OUT / f"{name}.bin")
            anims = sorted(sp.get("anims", {}).items(), key=lambda kv: kv[1]["row"])
            sprites.append((name, sp["cell"], anims))
            print(f"sprite  {name:24} {w}x{h} cell {sp['cell']} anims {len(anims)}")

    tj = SHEETS / "terrain" / "terrain.json"
    if tj.exists():
        t = json.loads(tj.read_text())
        themes = t.get("themes", t)
        items = themes.items() if isinstance(themes, dict) else enumerate(themes)
        for key, th in items:
            idx = int(th.get("index", key))
            entry = {"index": idx}
            for kind in ("wall", "water"):
                f = th.get(f"{kind}_atlas") or th.get(kind) or f"theme{idx}_{kind}.png"
                if isinstance(f, dict):
                    f = f.get("file", f"theme{idx}_{kind}.png")
                src = SHEETS / "terrain" / Path(f).name
                if src.exists():
                    blob(src, OUT / f"terrain{idx}_{kind}.bin")
                    entry[kind] = True
            decos = th.get("deco") or th.get("decos") or th.get("deco_files") or []
            if isinstance(decos, dict):
                decos = list(decos.values())
            entry["deco"] = []
            for k, f in enumerate(decos):
                f = f["file"] if isinstance(f, dict) else f
                src = SHEETS / "terrain" / Path(f).name
                if src.exists():
                    blob(src, OUT / f"terrain{idx}_deco{k}.bin")
                    entry["deco"].append(k)
            terrain.append(entry)
            print(f"terrain {idx}: {entry}")

    lines = [
        "// @generated by scripts/import_art.py -- do not edit by hand.",
        "use crate::art::{AnimDef, SheetDef, TerrainDef};",
        "",
        "pub static SHEETS: &[SheetDef] = &[",
    ]
    for name, cell, anims in sprites:
        a = ", ".join(
            f"AnimDef {{ name: {rust_str(k)}, row: {v['row']}, frames: {v['frames']}, fps: {v.get('fps', 8)} }}"
            for k, v in anims
        )
        lines.append(
            f"    SheetDef {{ name: {rust_str(name)}, cell: ({cell[0]}, {cell[1]}), "
            f"data: include_bytes!(\"../assets/art/{name}.bin\"), anims: &[{a}] }},"
        )
    lines += ["];", "", "pub static TERRAIN: &[TerrainDef] = &["]
    for e in sorted(terrain, key=lambda e: e["index"]):
        i = e["index"]
        wall = f'Some(include_bytes!("../assets/art/terrain{i}_wall.bin"))' if e.get("wall") else "None"
        water = f'Some(include_bytes!("../assets/art/terrain{i}_water.bin"))' if e.get("water") else "None"
        deco = ", ".join(f'include_bytes!("../assets/art/terrain{i}_deco{k}.bin")' for k in e["deco"])
        lines.append(f"    TerrainDef {{ theme: {i}, wall: {wall}, water: {water}, deco: &[{deco}] }},")
    lines += ["];", ""]
    GEN.write_text("\n".join(lines), newline="\n")
    print(f"wrote {GEN.relative_to(ROOT)}: {len(sprites)} sheets, {len(terrain)} terrain themes")


if __name__ == "__main__":
    main()
