// @generated by scripts/import_art.py -- do not edit by hand.
use crate::art::{AnimDef, SheetDef, TerrainDef};

pub static SHEETS: &[SheetDef] = &[
    SheetDef { name: "mage_earth", cell: (24, 40), data: include_bytes!("../assets/art/mage_earth.bin"), anims: &[AnimDef { name: "idle_down", row: 0, frames: 1, fps: 2 }, AnimDef { name: "idle_up", row: 1, frames: 1, fps: 2 }, AnimDef { name: "idle_side", row: 2, frames: 1, fps: 2 }, AnimDef { name: "walk_down", row: 3, frames: 4, fps: 8 }, AnimDef { name: "walk_up", row: 4, frames: 4, fps: 8 }, AnimDef { name: "walk_side", row: 5, frames: 4, fps: 8 }] },
    SheetDef { name: "mage_fire", cell: (24, 40), data: include_bytes!("../assets/art/mage_fire.bin"), anims: &[AnimDef { name: "idle_down", row: 0, frames: 1, fps: 2 }, AnimDef { name: "idle_up", row: 1, frames: 1, fps: 2 }, AnimDef { name: "idle_side", row: 2, frames: 1, fps: 2 }, AnimDef { name: "walk_down", row: 3, frames: 4, fps: 8 }, AnimDef { name: "walk_up", row: 4, frames: 4, fps: 8 }, AnimDef { name: "walk_side", row: 5, frames: 4, fps: 8 }] },
    SheetDef { name: "mage_ice", cell: (24, 40), data: include_bytes!("../assets/art/mage_ice.bin"), anims: &[AnimDef { name: "idle_down", row: 0, frames: 1, fps: 2 }, AnimDef { name: "idle_up", row: 1, frames: 1, fps: 2 }, AnimDef { name: "idle_side", row: 2, frames: 1, fps: 2 }, AnimDef { name: "walk_down", row: 3, frames: 4, fps: 8 }, AnimDef { name: "walk_up", row: 4, frames: 4, fps: 8 }, AnimDef { name: "walk_side", row: 5, frames: 4, fps: 8 }] },
    SheetDef { name: "mage_storm", cell: (24, 40), data: include_bytes!("../assets/art/mage_storm.bin"), anims: &[AnimDef { name: "idle_down", row: 0, frames: 1, fps: 2 }, AnimDef { name: "idle_up", row: 1, frames: 1, fps: 2 }, AnimDef { name: "idle_side", row: 2, frames: 1, fps: 2 }, AnimDef { name: "walk_down", row: 3, frames: 4, fps: 8 }, AnimDef { name: "walk_up", row: 4, frames: 4, fps: 8 }, AnimDef { name: "walk_side", row: 5, frames: 4, fps: 8 }] },
];

pub static TERRAIN: &[TerrainDef] = &[
];
