// Generated by scripts/import_levels.py - do not edit.
/// (file name, JSON text) for every built-in level.
pub const LEVELS: &[(&str, &str)] = &[
    ("cave_2.json", include_str!("../levels/cave_2.json")),
];
