// Generated by scripts/import_levels.py - do not edit.
/// (file name, JSON text) for every built-in level.
pub const LEVELS: &[(&str, &str)] = &[
    ("cave_2.json", include_str!("../levels/cave_2.json")),
    ("lair_1.json", include_str!("../levels/lair_1.json")),
    ("lair_2.json", include_str!("../levels/lair_2.json")),
    ("lair_3.json", include_str!("../levels/lair_3.json")),
    ("lair_4.json", include_str!("../levels/lair_4.json")),
    ("lair_5.json", include_str!("../levels/lair_5.json")),
    ("lair_6.json", include_str!("../levels/lair_6.json")),
];
